language: node_js
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage && codecov
notifications:
  email:
    - on_failure: change